In [5]:
from database.deps import createAdminClient, DATABASE_ID, TRANSACTIONSUMMARY_COLLECTION_ID
from appwrite.services.databases import Databases
from appwrite.permission import Permission
from appwrite.role import Role
from database.transaction_dao import TransactionDao
# from models.receive.transactions import Transactions_ing, Transactions_revolut, Transactions_shinha
import secrets
from appwrite.query import Query
import pandas as pd

In [1]:
def get_conversion_rate(from_currency, to_currency):
    currency = {0:  "EUR", 1: "KRW", 2: "KES", 3: "GBP"}

    from_currency = currency[from_currency]
    to_currency = currency[to_currency]

    exchange_table = pd.read_csv('/Users/sginikwo/goldy-personal/co-finance-backend/database/exchange_rates.csv', index_col=0)
    # Return 1 if both currencies are the same
    if from_currency == to_currency:
        return 1
    else:
        return exchange_table.loc[from_currency, to_currency]

In [3]:
import os
os.chdir("/Users/sginikwo/goldy-personal/co-finance-backend")

In [6]:
from database.deps import createAdminClient, DATABASE_ID, TRANSACTIONSUMMARY_COLLECTION_ID
from appwrite.services.databases import Databases
from appwrite.permission import Permission
from appwrite.role import Role
from database.transaction_dao import TransactionDao
# from models.receive.transactions import Transactions_ing, Transactions_revolut, Transactions_shinha
import secrets
from appwrite.query import Query
import pandas as pd
# from models.send.userToken import get_insert_data

client = createAdminClient()
db = Databases(client)

class Summary:
  def __init__(self):
    self.db_id = DATABASE_ID
    self.collection_id = TRANSACTIONSUMMARY_COLLECTION_ID

  
  def save(self):
    # currency = {0: "EUR", 1: "KRW", 2:  "KES", 3: "GBP", 4: "USD"}
    # base = currency[user_data[0]]
    # target = currency[user_data[1]]

    transactions = TransactionDao().get_transactions(user_data="67618a6b0015560030e5")

    # for row in data:
    #   pass

    # result = db.list_documents(
    #         database_id= self.db_id,
    #         collection_id= self.collection_id,
    #         queries=[
    #         Query.equal("base", base),  # Add double quotes around base
    #         Query.equal("target", target),  # Add double quotes around target
    #     ]
    #     )
    
    # rate = result["documents"][0]["rate"]
    return transactions

  

sum = Summary()

transactions = sum.save()



df = pd.DataFrame.from_dict(transactions)

# display(df)

for trans in transactions:
  print()
  print(trans)
  print()

{'id': '7bc4f09314227bd2', 'date': '2024-12-05', 'recipient': 'AAB INZ TIKKIE', 'currency': 0, 'amount': '100.00', 'transactionType': 'Transfer', 'transactionDetails': 'Name: AAB INZ TIKKIE Description: Tikkie ID 000937426748, Goldy, Van AE INIKWO, NL02ABNA0624031594 IBAN: NL13ABNA0506417344 Reference: 937426748 Date/time: 05-12-2024 15:42:36 Value date: 05/12/2024', 'icon': 0, 'userCurrency': 0, 'balance': '205.44', '$id': 'ff9d99c85e87f907', '$createdAt': '2024-12-28T19:32:45.997+00:00', '$updatedAt': '2024-12-28T19:32:45.997+00:00', '$databaseId': '6758d83b003553fc7077', '$collectionId': '6758d8910039a6caf2c7'}


{'id': '9f5a15d3f6416fc6', 'date': '2024-12-01', 'recipient': 'OMWARE GLO', 'currency': 1, 'amount': '-1100000', 'transactionType': '안양법', 'transactionDetails': '모바일', 'icon': 0, 'userCurrency': 0, 'balance': '1259346', '$id': '73b7a0e7b90a193d', '$createdAt': '2024-12-24T01:45:07.643+00:00', '$updatedAt': '2024-12-24T01:45:07.643+00:00', '$databaseId': '6758d83b003553fc7077', '$collectionId': '6758d8910039a6caf2c7'}


{'id': '4a487848aec47a8f', 'date': '2019-11-08', 'recipient': 'Auth *3200', 'currency': 3, 'amount': '1.00', 'transactionType': 'TOPUP', 'transactionDetails': 'Auth *3200', 'icon': 0, 'userCurrency': 0, 'balance': '0', '$id': 'ba71f8a73b5670c1', '$createdAt': '2024-12-24T01:45:17.783+00:00', '$updatedAt': '2024-12-24T01:45:17.783+00:00', '$databaseId': '6758d83b003553fc7077', '$collectionId': '6758d8910039a6caf2c7'}

In [7]:
display(df)

,id,date,recipient,currency,amount,transactionType,transactionDetails,icon,userCurrency,balance,$id,$createdAt,$updatedAt,$databaseId,$collectionId
0,7bc4f09314227bd2,2024-12-05,AAB INZ TIKKIE,0,100.00,Transfer,Name: AAB INZ TIKKIE Description: Tikkie ID 00...,0,0,205.44,ff9d99c85e87f907,2024-12-28T19:32:45.997+00:00,2024-12-28T19:32:45.997+00:00,6758d83b003553fc7077,6758d8910039a6caf2c7
1,9f5a15d3f6416fc6,2024-12-01,OMWARE GLO,1,-1100000,안양법,모바일,0,0,1259346,73b7a0e7b90a193d,2024-12-24T01:45:07.643+00:00,2024-12-24T01:45:07.643+00:00,6758d83b003553fc7077,6758d8910039a6caf2c7
2,4a487848aec47a8f,2019-11-08,Auth *3200,3,1.00,TOPUP,Auth *3200,0,0,0,ba71f8a73b5670c1,2024-12-24T01:45:17.783+00:00,2024-12-24T01:45:17.783+00:00,6758d83b003553fc7077,6758d8910039a6caf2c7

In [ ]:
# Convert 'date' to datetime and extract year, month, day
df['date'] = pd.to_datetime(df['date'])
df['day'], df['month'], df['year'] = df['date'].dt.day.astype(int), df['date'].dt.month_name(), df['date'].dt.year.astype(int)

# Convert 'amount' and 'balance' to userCurrency
df[['amount', 'balance']] = df.apply(
    lambda row: row[['amount', 'balance']].astype(float) * get_conversion_rate(row['currency'], row['userCurrency']),
    axis=1
)

In [20]:
# Convert 'date' to datetime and extract year, month, day
df['date'] = pd.to_datetime(df['date'])
df['day'], df['month'], df['year'] = df['date'].dt.day.astype(int), df['date'].dt.month_name(), df['date'].dt.year.astype(int)

# Convert 'amount' and 'balance' to userCurrency
df[['amount', 'balance']] = df.apply(
    lambda row: row[['amount', 'balance']].astype(float) * get_conversion_rate(row['currency'], row['userCurrency']),
    axis=1
)

# Convert 'amount' and 'balance' temporarily for calculations
df[['amount_num', 'balance_num']] = df[['amount', 'balance']].apply(pd.to_numeric, errors='coerce')

# Calculate monthlyBalance, monthlyExpenses, monthlySavings, and monthlyIncome
df['monthlyBalance'] = df.sort_values('date', ascending=True).groupby(['year', 'month'])['balance_num'].transform('last')
df['monthlyExpenses'] = df.groupby(['year', 'month'])['amount_num'].transform(lambda x: x[x < 0].sum())
df['monthlySavings'] = df.groupby(['year', 'month'])['amount_num'].transform(
    lambda x: x[df['recipient'].str.contains('Spaarrekening|Trade Republic', case=False, na=False)].sum())
df['monthlyIncome'] = df.groupby(['year', 'month'])['amount_num'].transform(lambda x: x[x > 0].sum())

# Drop temporary numeric columns and unwanted columns
# df.drop(columns=['amount_num', 'balance_num', 'date_str'], inplace=True)
df["transactionId"] = df["id"]
df["monthlyInvestment"] = None

df["date"] = pd.to_datetime(df["date"], format="%Y-%m-%d")  # Adjust format as needed
max_date = df["date"].max().strftime("%Y-%m-%d")
df["date"] = df["date"].astype(str)

# Select the desired columns
df = df[["date", 'day', 'month', 'year', 'monthlyBalance', 'monthlyExpenses', 'monthlySavings', "monthlyInvestment", "transactionId", 'monthlyIncome']]

In [24]:
df = df.sort_values(by="date", ascending=True)

In [ ]:
display(df)

In [200]:
df["date"] = pd.to_datetime(df["date"], format="%Y-%m-%d")  # Adjust format as needed
max_date = df["date"].max().strftime("%Y-%m-%d")

In [ ]:
pp = df["date"].astype(str)

In [ ]:
print(type(pp[0]))

In [ ]:
print(max_date)

In [ ]:
print( "2024-12-05" < "2024-12-01")

In [150]:
# Keep the original date as a string
df['date_str'] = df['date']

# Convert the date column to datetime for calculations
df['date'] = pd.to_datetime(df['date'])

# Extract year, month, and day from the date column
df['date'] = pd.to_datetime(df['date'])
df['day'] = df['date'].dt.day.astype(int)  # Convert day to integer
df['month'] = df['date'].dt.month_name()
df['year'] = df['date'].dt.year.astype(int)  # Convert year to integer

# Add the conversion to the userCurrency for amount data
df['amount'] = df.apply(
    lambda row: float(row['amount']) * get_conversion_rate(row['currency'], row['userCurrency'])
    if pd.notnull(row['amount']) else None, axis=1)

# Add the conversion to the userCurrency for balance data
df['balance'] = df.apply(
    lambda row: float(row['balance']) * get_conversion_rate(row['currency'], row['userCurrency'])
    if pd.notnull(row['balance']) else None, axis=1)

# Convert amount and balance temporarily for calculations
df['amount_num'] = pd.to_numeric(df['amount'], errors='coerce')
df['balance_num'] = pd.to_numeric(df['balance'], errors='coerce')

# Calculate monthlyBalance (latest balance of the month)
df['monthlyBalance'] = df.sort_values('date', ascending=True).groupby(['year', 'month'])['balance_num'].transform('last').astype(str)

# Calculate total monthlyExpenses (sum of all negative amounts)
df['monthlyExpenses'] = df.groupby(['year', 'month'])['amount_num'].transform(
    lambda x: x[x < 0].sum()
).astype(str)

# Calculate total monthlySavings (sum of amounts with specific recipients)
df['monthlySavings'] = df.groupby(['year', 'month'])['amount_num'].transform(
    lambda x: x[
        df['recipient'].str.contains('Spaarrekening|Trade Republic', case=False, na=False)
    ].sum()
).astype(str)

# Calculate total monthlyIncome (sum of all positive amounts)
df['monthlyIncome'] = df.groupby(['year', 'month'])['amount_num'].transform(
    lambda x: x[x > 0].sum()
).astype(str)

# Drop temporary numeric columns
df.drop(columns=['amount_num', 'balance_num'], inplace=True)

# Rename 'date_str' back to 'date' to keep the original format
df['date'] = df['date_str']
df.drop(columns=['date_str'], inplace=True)

# Select the desired columns
df = df[['currency', 'userCurrency', 'id', 'date', 'recipient', 'currency', 'amount',
         'transactionDetails', 'balance', 'day', 'month',
         'year', 'monthlyBalance', 'monthlyExpenses', 'monthlySavings', 'monthlyIncome']]

In [ ]:
display(df)

In [ ]:
df.to_dict()

In [ ]:
display(df)

In [ ]:
import secrets
import requests
import pandas as pd
from appwrite.client import Client
from appwrite.services.databases import Databases

from deps import createAdminClient, DATABASE_ID, CURRENCY_COLLECTION_ID


# Initialize Appwrite Client
client = createAdminClient()
db = Databases(client)


# Dictionary of currencies
currency = {"EUR": 0, "KRW": 1, "KES": 2, "GBP": 3}

# API base URL
api_url = "https://hexarate.paikama.co/api/rates/latest"

# Initialize the exchange rate table
currencies = list(currency.keys())
exchange_table = pd.DataFrame(index=currencies, columns=currencies)

# Fetch exchange rates and populate the table
for base in currencies:
    for target in currencies:
        if base == target:
            exchange_table.loc[base, target] = 1.0  # Same currency exchange rate is 1
        else:
            # Call Hexarate API
            response = requests.get(f"{api_url}/{base}?target={target}")
            if response.status_code == 200:
                response_data = response.json()
                rate = response_data.get("data", {}).get("mid")  # Extract 'mid' from 'data'
                exchange_table.loc[base, target] = rate
            else:
                exchange_table.loc[base, target] = None  # Mark as None if request fails

exchange_table.to_csv("exchange_rates.csv")

# Save or update exchange rates in Appwrite database
for base in currencies:
    for target in currencies:
        rate = exchange_table.loc[base, target]
        if rate is not None:  # Only process valid rates
            document_data = {
                "base": base,
                "target": target,
                "rate": rate
            }

            # Check if the document already exists
            query = [
                Query.equal('base', base),
                Query.equal('target', target)
            ]
            try:

                existing_documents = db.list_documents(
                    database_id=DATABASE_ID,
                    collection_id=CURRENCY_COLLECTION_ID,
                    queries=query
                ).get("documents", [])

                if existing_documents:
                    # Update the existing document
                    document_id = existing_documents[0]["$id"]
                    db.update_document(
                        database_id=DATABASE_ID,
                        collection_id=CURRENCY_COLLECTION_ID,
                        document_id=document_id,
                        data=document_data
                    )
                    print(f"Updated rate {base} to {target}: {rate}")
                else:
                    # Create a new document
                    db.create_document(
                        database_id=DATABASE_ID,
                        collection_id=CURRENCY_COLLECTION_ID,
                        document_id=secrets.token_hex(8),  # Auto-generate unique document IDs
                        data=document_data
                    )
                    print(f"Created rate {base} to {target}: {rate}")
            except Exception as e:
                print(f"Error processing rate {base} to {target}: {e}")

In [1]:
import os
os.chdir("/Users/sginikwo/goldy-personal/co-finance-backend")

In [8]:
from database.deps import createAdminClient, DATABASE_ID, TRANSACTIONSUMMARY_COLLECTION_ID
from appwrite.services.databases import Databases
from appwrite.permission import Permission
from appwrite.role import Role
from models.send.transactionSummary_data import custom_summary, get_insert_data
from database.transaction_dao import TransactionDao
import secrets
from appwrite.query import Query
import pandas as pd


client = createAdminClient()
db = Databases(client)

class Summary:
  def __init__(self):
    self.db_id = DATABASE_ID
    self.collection_id = TRANSACTIONSUMMARY_COLLECTION_ID

  
  def get_summary(self, user_data=None):
    result = db.list_documents(
      database_id = self.db_id,
      collection_id = self.collection_id,
      queries=[
                Query.order_desc("date"),  # Sort by "name" in ascending order
            ]
    )
    for rsul in result["documents"]:
      rsul.pop("userId", None)
      rsul.pop('$permissions', None)

    return result['documents']

  def get_custom_summary(self):
    transactions = self.get_summary()

    response = custom_summary(transactions)
    return response
  
  def push_data(self):
    transactions = TransactionDao().get_transactions(user_data="67618a6b0015560030e5")

    data = get_insert_data(transactions)

    exist_summary = self.get_summary()

    for row in data[0]:
      if exist_summary:
        if exist_summary[0]["date"] == row["date"]:
          results = [(entry['date'], entry['$id']) for entry in exist_summary]

          for result in results:
            if result[0] == row["date"]:

              db.update_document(
                  database_id= self.db_id,
                  collection_id= self.collection_id,
                  document_id= result[1],
                  data=row,
                  permissions=[
                      Permission.read(Role.user("67618a6b0015560030e5")),
                      Permission.update(Role.user("67618a6b0015560030e5")),
                      Permission.delete(Role.user("67618a6b0015560030e5"))
                  ]
              )
      else:
        db.create_document(
          database_id= self.db_id,
          collection_id= self.collection_id,
          document_id=secrets.token_hex(8),
          data=row,
          permissions=[
              Permission.read(Role.user("67618a6b0015560030e5")),
              Permission.update(Role.user("67618a6b0015560030e5")),
              Permission.delete(Role.user("67618a6b0015560030e5"))
          ]
        )
    

    return transactions
  

summary = Summary()

summary.push_data()
# print(summary.get_custom_summary())

TypeError: string indices must be integers, not 'str'

In [ ]:
# Ensure date column is datetime
df['date'] = pd.to_datetime(df['date'])

# Get latest month's data
latest_month = df['date'].max().month
latest_year = df['date'].max().year
latest_data = df[(df['date'].dt.month == latest_month) & (df['date'].dt.year == latest_year)]

# Extract balance, expenses, and savings
latest_summary = latest_data[['monthlyBalance', 'monthlyExpenses', 'monthlySavings']].drop_duplicates()

latest_summary.to_dict(orient='records')

In [ ]:
display(dd)

In [ ]:
!pwd

In [ ]:
data = [
    {'day': 5, 'month': 'December', 'year': 2024, 'monthlyBalance': '20544.0', 'monthlyExpenses': '-719.1932', 'monthlySavings': '0.0', 'monthlyInvestment': '', 'transactionId': '9fbd609943048a8b', 'monthlyIncome': '100.0', 'date': '2024-12-05', '$id': '7f987a37ee81891c', '$createdAt': '2024-12-28T14:38:23.979+00:00', '$updatedAt': '2024-12-28T14:38:23.979+00:00', '$databaseId': '6758d83b003553fc7077', '$collectionId': '676dcdf30020bde2a475'},
    {'day': 1, 'month': 'December', 'year': 2024, 'monthlyBalance': '20544.0', 'monthlyExpenses': '-719.1932', 'monthlySavings': '0.0', 'monthlyInvestment': '', 'transactionId': '9f5a15d3f6416fc6', 'monthlyIncome': '100.0', 'date': '2024-12-01', '$id': 'aa9b71a38edc1428', '$createdAt': '2024-12-28T14:38:24.107+00:00', '$updatedAt': '2024-12-28T14:38:24.107+00:00', '$databaseId': '6758d83b003553fc7077', '$collectionId': '676dcdf30020bde2a475'},
    {'day': 8, 'month': 'November', 'year': 2019, 'monthlyBalance': '0.0', 'monthlyExpenses': '0.0', 'monthlySavings': '0.0', 'monthlyInvestment': '', 'transactionId': '4a487848aec47a8f', 'monthlyIncome': '1.20201', 'date': '2019-11-08', '$id': '0832a315dab3519a', '$createdAt': '2024-12-28T14:38:24.254+00:00', '$updatedAt': '2024-12-28T14:38:24.254+00:00', '$databaseId': '6758d83b003553fc7077', '$collectionId': '676dcdf30020bde2a475'}
]

# Extracting date and $id as tuples
result = [(entry['date'], entry['$id']) for entry in data]

print(result)

In [ ]:
for date in result:
  print(date[0])